version: 2
updates:
# Fetch and update latest `cargo` packages
- package-ecosystem: cargo
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - toxicmender
  assignees:
    - toxicmender
  commit-message:
    prefix: dep
    prefix-development: chore
    include: scope
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - toxicmender
  assignees:
    - toxicmender
  commit-message:
    prefix: dep
    prefix-development: chore
    include: scope
